// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7X_ijW6RXorSAaNt9M6ASBDLyEQIxAag',
    appId: '1:448948961427:web:77dd3cdb65b827e44fcd66',
    messagingSenderId: '448948961427',
    projectId: 'forum-3b899',
    authDomain: 'forum-3b899.firebaseapp.com',
    databaseURL: 'https://forum-3b899-default-rtdb.firebaseio.com',
    storageBucket: 'forum-3b899.firebasestorage.app',
    measurementId: 'G-F5J5W3GFCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgLSUjROM9FIATCIgJLffUZa78Vos_z38',
    appId: '1:448948961427:android:185a828f10dc39ca4fcd66',
    messagingSenderId: '448948961427',
    projectId: 'forum-3b899',
    databaseURL: 'https://forum-3b899-default-rtdb.firebaseio.com',
    storageBucket: 'forum-3b899.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7dZOxmAuuIfVLEwODeQCE1cBeeQHQJw',
    appId: '1:448948961427:ios:cc12aad835d49d2c4fcd66',
    messagingSenderId: '448948961427',
    projectId: 'forum-3b899',
    databaseURL: 'https://forum-3b899-default-rtdb.firebaseio.com',
    storageBucket: 'forum-3b899.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7dZOxmAuuIfVLEwODeQCE1cBeeQHQJw',
    appId: '1:448948961427:ios:cc12aad835d49d2c4fcd66',
    messagingSenderId: '448948961427',
    projectId: 'forum-3b899',
    databaseURL: 'https://forum-3b899-default-rtdb.firebaseio.com',
    storageBucket: 'forum-3b899.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7X_ijW6RXorSAaNt9M6ASBDLyEQIxAag',
    appId: '1:448948961427:web:2e04975cdeab6e614fcd66',
    messagingSenderId: '448948961427',
    projectId: 'forum-3b899',
    authDomain: 'forum-3b899.firebaseapp.com',
    databaseURL: 'https://forum-3b899-default-rtdb.firebaseio.com',
    storageBucket: 'forum-3b899.firebasestorage.app',
    measurementId: 'G-C876G97HFE',
  );
}
